version: '3.3'

services:
  devpi:
    restart: always
    build:
      context: ./devpi
      args:
          GIT_VERSION: ${GIT_VERSION}
          PROJECT_NAME: ${PROJECT_NAME}
          PROJECT_URL: ${PROJECT_URL}
          BUILD_DATE: ${BUILD_DATE}
          LDAP_SEARCH_PASSWORD: ${LDAP_SEARCH_PASSWORD}
      labels:
        maintainer: "${MAINTAINER}"
        org.label-schema.schema-version: "1.0"
        org.label-schema.description: "Local, caching, python package index"
        org.label-schema.url: "${PROJECT_URL}"
        org.label-schema.vcs: "${GIT_SHA}"
        org.label-schema.version: "${GIT_VERSION}"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.docker.cmd: "docker-compose"
    expose:
      - 4040
    ports:
      - 6969:4040
    volumes:
      - server:/devpi/server
      - server-upgrade:/devpi/server-upgrade
    networks:
      - devpinet

  areplica:
    restart: always
    build:
      context: ./replica
      args:
          GIT_VERSION: ${GIT_VERSION}
          PROJECT_NAME: ${PROJECT_NAME}
          PROJECT_URL: ${PROJECT_URL}
          BUILD_DATE: ${BUILD_DATE}
      labels:
        maintainer: "${MAINTAINER}"
        org.label-schema.schema-version: "1.0"
        org.label-schema.description: "Local, caching, python package index"
        org.label-schema.url: "${PROJECT_URL}"
        org.label-schema.vcs: "${GIT_SHA}"
        org.label-schema.version: "${GIT_VERSION}"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.docker.cmd: "docker-compose"
    environment:
      - REP_PORT=4041
      - MASTER_URL=http://devpi:4040
    expose:
      - 4041
    ports:
      - 6971:4041
    depends_on:
      - devpi
    networks:
      - devpinet

  nginx:
    restart: always
    build:
      context: ./nginx
      args:
          OUTER_PORT: ${OUTER_PORT}
          OUTER_SSL_PORT: ${OUTER_SSL_PORT}
      labels:
        maintainer: "${MAINTAINER}"
        org.label-schema.schema-version: "1.0"
        org.label-schema.description: "Load balancer for a local, caching, python package index setup"
        org.label-schema.url: "${PROJECT_URL}"
        org.label-schema.vcs: "${GIT_SHA}"
        org.label-schema.version: "${GIT_VERSION}"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.docker.cmd: "docker-compose"
    ports:
      - ${OUTER_PORT}:8080
      - ${OUTER_SSL_PORT}:8443
    volumes:
      - server:/devpi/server
      - server-upgrade:/devpi/server-upgrade
    depends_on:
      - devpi
    networks:
      - devpinet

networks:
  devpinet:
      driver: bridge

volumes:
  server:
  server-upgrade:
